version: '3'
services:
        web:
                image: flask_bestgroup_v1
                build: .
                ports:
                        - "8062:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
